### ISSUE TITLE
show several webpage into my window page using streamlit

### ISSUE THREAD

**Issue by devilution1979** [Sven-Bo/personal-website-streamlit#4]
Hello Sven,
 I am a new on Streamlit and try to learn it at your youtube channel. I had some problem when I need to grab 2 or 3 website name, such as www.google.com and facebook.com and put into my new webpage. BUT in this case I only using 1 webpage, after running streamlit it shown some message "www.google.com refused to connect."

this is my pyhton code:
import streamlit as st

def main():
    st.title("Embedding External Website")

   
    st.markdown('<iframe src="https://www.google.com" width="600" height="400"></iframe>', unsafe_allow_html=True)

if __name__ == "__main__":
    main()

i'm using streamlit version= 1.22.0
and also I tried to set Streamlit by used this port, but still failed
streamlit run my_app.py --server.port=80

Kindly please need you help and advise.

Danke.
:)

**Comment by Sven-Bo** [comment]
@devilution1979 Thank you for reaching out. However, this issue doesn't seem related to the codebase of this repository. If you have questions or issues specifically related to the project, please feel free to open a new one. Closing this for now.
Thanks for your understanding.
